version: 2.1
orbs:
  node: circleci/node@3.0.0
  aws-cli: circleci/aws-cli@1.3.2

jobs:
  deploy:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - aws-cli/setup
      - node/install-packages
      - run:
          name: deploy
          command: npm run deploy

workflows:
  tests:
    jobs:
      - node/test
      - deploy:
          requires:
            - node/test
          filters:
            branches:
                only: main

